[frontend]
frontend-instance-1 ansible_host=13.221.158.79

[backend]
backend-instance-1 ansible_host=10.0.2.202

[db]
db-instance-1 ansible_host=10.0.2.180


[all:vars]
ansible_user=ec2-user
ansible_ssh_private_key_file="/Users/egurnat/Desktop/Ironhack/natavan-useast1-dvft.pem"
ansible_ssh_common_args='-o ProxyCommand="ssh -W %h:%p -i /Users/egurnat/Desktop/Ironhack/natavan-useast1-dvft.pem ec2-user@13.221.158.79" -o StrictHostKeyChecking=no'

